# config.yaml

# Specify path to DB
DB: "/home/administrator/phd/ICTV_DB/DB_2024/CRASSIFY_DB.dmnd"

# Specify path to your input file
input_files:
  - path: "/home/administrator/phd/crassify_v2/sample_data/test_phages_nucl/pooled_test_phages.fna" 
    type: "nucleotide"  # or "protein"

# Specify path to your target DB proteome metadata (default is crassify metadata)
metadata: "/home/administrator/phd/ICTV_DB/DB_2024/ICTV_metadata.csv"

output_directory: "/home/administrator/phd/"

# Path to decenttree installation
decenttree: "/home/administrator/programs/decenttree/build/decenttree"


