# config.yaml

input:
  type: nucleotide
  path: /sample_data/test_phages_nucl/pooled_test_phages.fna

db:
  dmnd: data/crassify_DB_2025.dmnd
  metadata: data/crassify_metadata.csv

# Crassify will create results folder in path e.g. /home/administrator/phd/crassify_out_2025-09-02
outdir: /home/administrator/phd/

# Path to decenttree installation
decenttree: /data/programs/decenttree

steps:
  translate: true
  diamond: true
  crassify: true
  decenttree: false
  dendogram: false
  visualize: true